quiz/urls.py
from django.urls import path
from django.conf import settings
from django.contrib.auth import views as auth_views

from . import views, api

app_name = 'quiz'
urlpatterns = [
    # HOME
    path('', views.index, name='index'),
    # QUESTION workflow
    path('question', views.question_home, name='question_home'),
    path('question/<int:question_id>/reservation',
         views.reservation,
         name='reservation'),
    path('question/<int:question_id>/reservation/steer',
         views.reservation_steer,
         name='reservation_steer'),
    path('question/<int:question_id>/reservation/lost/<str:approved_player>',
         views.reservation_lost,
         name='reservation_lost'),
    path('question/<int:question_id>/reservation/<int:reservation_id>/answer/',
         views.provide_answer,
         name='provide_answer'),
    path('question/<int:question_id>/answer/<int:answer_id>/steer',
         views.answer_steer,
         name='answer_steer'),
    # ACCOUNT: Signup, login, logout
    path('signup', views.signup, name='signup'),
    path('login',
         auth_views.LoginView.as_view(
             template_name='quiz/account/login.html'
         ),
         {'next_page': settings.LOGIN_REDIRECT_URL},
         name='login'),
    path('logout',
         auth_views.LogoutView.as_view(),
         {'next_page': settings.LOGOUT_REDIRECT_URL},
         name='logout'),
    # APIs
    path('api/check_question_reservation/<int:question_id>',
         api.api_check_question_reservation,
         name='api_check_question_reservation'),
    path('api/check_answer_status/<int:answer_id>',
         api.api_check_answer_status,
         name='api_check_answer_status'),
]

quiz_challenge/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
	path('', include('quiz.urls')),
    path('admin/', admin.site.urls),
]

quiz/forms.py
#!/usr/bin/env python

from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import Player, Answer


class PlayerCreationForm(forms.ModelForm):
    """
    A custom form for creating new :model:`quiz.Player` instance.
    Includes all the required fields, plus a repeated password.
    """
    password1 = forms.CharField(
        label='Password',
        widget=forms.PasswordInput
    )
    password2 = forms.CharField(
        label='Password confirmation',
        widget=forms.PasswordInput
    )

    class Meta:
        model = Player
        fields = ('nickname',)

    def clean_password2(self):
        """
        Check that the two password entries match and return
        the verified password.
        """
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        """
        Save the provided password in hashed format.
        Return an instance of :model:`quiz.Player`.
        """
        player = super().save(commit=False)
        player.set_password(self.cleaned_data["password1"])

        if commit:
            player.save()

        return player


class PlayerChangeForm(forms.ModelForm):
    """
    A form for update a :model:`quiz.Player` instance.
    Includes all the fields on the user, but replaces the password field
    with admin's password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = Player
        fields = ('nickname', 'password', 'is_active', 'is_admin')

    def clean_password(self):
        """Return the initial password."""
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class AnswerCreationForm(forms.ModelForm):
    """
    A custom form for creating new :model:`quiz.Answer` instances.
    Includes all the required fields.
    """
    answer_text = forms.CharField(
        label='Answer',
        widget=forms.Textarea(attrs={'rows':4}),
    )

    class Meta:
        model = Answer
        fields = ('answer_text',)

    def save(self, commit=True):
        """
        Override default Django save method.
        Return a instance of :model:`quiz.Answer`.
        """
        answer = super().save(commit=False)

        if commit:
            answer.save()

        return answer

quiz/views.py
#!/usr/bin/env python

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login

from .models import Question, Reservation, Player, Answer
from .forms import PlayerCreationForm, AnswerCreationForm


def index(request):
    """
    Display the intro page of the app.

    **Template:**

    :template:`quiz/index.html`
    """
    return render(request, 'quiz/index.html')


@login_required()
def question_home(request):
    """
    The home page of the game, display an individual :model:`quiz.Question`.
    Allows the player to reserve it using a button.

    **Context**

    ``online_players``
        A query using the :model:`quiz.Player` manager.
    ``question``
        An instance of :model:`quiz.Question`.
    ``available_questions``
        A query using the :model:`quiz.Question` manager.

    **Template:**

    :template:`quiz/question/home.html`
        If a question is available.
    :template:`quiz/question/no_questions.html`
        If there are no LIVE questions.
    """
    # page templates
    page_template_show_question = 'quiz/question/home.html'
    page_template_no_questions = 'quiz/question/no_questions.html'

    # Check if there are new questions
    # By 'new' it means with status 'live'
    try:
        available_questions = Question.objects.filter(
            status=Question.STATUS_LIVE
        ).order_by('-creation_date')[:1]

        # Get the question to be displayed
        current_question = available_questions.get()

        # select the correct template
        page_template = page_template_show_question

    except Question.DoesNotExist:
        current_question = None
        page_template = page_template_no_questions

    return render(request, page_template, {
        'online_players': Player.objects.get_online_players(),
        'question': current_question,
        'available_questions': Question.objects.questions_available()
    })


@login_required()
def reservation(request, question_id):
    """
    The second step of the the game: the player has reserved a question.
    A :model:`quiz.Reservation` object will be created here
    (only if it's the first time).

    question_id is the id of the :model:`quiz.Question` to show.

    Redirects to :view:`quiz.question_home` if there's no
    :model:`quiz.Question` with question_id.

    **Context**

    ``online_players``
        A query using the :model:`quiz.Player` manager.
    ``question``
        An instance of :model:`quiz.Question`.
    ``available_questions``
        A query using the :model:`quiz.Question` manager.

    **Template:**

    :template:`quiz/question/reservation.html`
    """
    page_template = 'quiz/question/reservation.html'

    # Retrieve the question from the id
    try:
        question = Question.objects.get(pk=question_id)

    except (KeyError, Question.DoesNotExist):
        # TODO: display a message
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('quiz:question_home'))

    # Get auth player info
    player = request.user

    # Check if a reservation has already been made by this player
    reservation_query = Reservation.objects.filter(
        question=question,
        player=player
    ).count()

    # If this is the first time and thus it's my first reservation,
    # then create one
    if reservation_query == 0:
        reservation = Reservation.objects.create_reservation(question, player)
        # TODO: display a message

    return render(request, page_template, {
        'online_players': Player.objects.get_online_players(),
        'question': question,
        'available_questions': Question.objects.questions_available()
    })


@login_required()
def reservation_steer(request, question_id):
    """
    This view steers the player based on the reservation approval result.
    If the players won, then they'll be redirected to the next phase,
    where an answer will be created and submitted.
    Otherwise, another view wll show he/she that he/she lost and can
    proceed with a new question.

    question_id is the id of the :model:`quiz.Question` to show.

    Redirect to :view:`quiz.provide_answer` if the player won the reservation,
    otherwise to :view:`quiz.reservation_lost`.
    Redirect to :view:`quiz.question_home` if there's no question with
    question_id.

    **Context**

    ``online_players``
        A query using the :model:`quiz.Player` manager.
    ``question``
        An instance of :model:`quiz.Question`.
    ``available_questions``
        A query using the :model:`quiz.Question` manager.
    """
    try:
        question = Question.objects.get(pk=question_id)

    except (KeyError, Question.DoesNotExist):
        # TODO: display a message
        return HttpResponseRedirect(reverse('quiz:question_home'))

    # Check if the player has won the reservation
    reservation_approved = Reservation.objects.filter(
        question=question, approved=True
    ).get()
    approved_player = str(reservation_approved.player.nickname)

    # Get authenticated/logged (current) player
    current_player = str(request.user)

    # If is the auth user that won, redirect to the answer page
    if approved_player == current_player:
        return HttpResponseRedirect(
            reverse('quiz:provide_answer',
                    args=(question.id, reservation_approved.id))
        )

    else:
        # Otherwise, to the lost page
        return HttpResponseRedirect(reverse(
                'quiz:reservation_lost',
                args=(question.id, approved_player,)
        ))


@login_required()
def reservation_lost(request, question_id, approved_player):
    """
    Display a 'you-lost' message.

    question_id is the id of the :model:`quiz.Question` to show.
    approved_player is the nickname of the :model:`quiz.Player` who
    won the reservation race.

    Redirect to :view:`quiz.question_home` if there's no
    :model:`quiz.Question` with question_id.

    **Context**

    ``online_players``
        A query using the :model:`quiz.Player` manager.
    ``question``
        An instance of :model:`quiz.Question`.
    ``approved_player``
        Nickname of a :model:`quiz.Player`.
    ``available_questions``
        A query using the :model:`quiz.Question` manager.

    **Template:**

    :template:`quiz/question/reservation_lost.html`
    """
    page_template = 'quiz/question_reservation_lost.html'

    try:
        question = Question.objects.get(pk=question_id)

    except (KeyError, Question.DoesNotExist):
        # TODO: display a message
        return HttpResponseRedirect(reverse('quiz:question_home'))

    return render(request, page_template, {
        'online_players': Player.objects.get_online_players(),
        'question': question,
        'approved_player': approved_player,
        'available_questions': Question.objects.questions_available()
    })


@login_required()
def provide_answer(request, question_id, reservation_id):
    """
    Display the current question and the form to provide an answer.
    When data is provided, it creates a :model:`quiz.Answer` object.

    question_id is the id of the :model:`quiz.Question` to show.
    reservation_id is the id of the :model:`quiz.Reservation` linked
    to the auth player and current question.

    Redirect to :view:`quiz.question_home` if there's no
    :model:`quiz.Question` with question_id or :model:`quiz.Reservation`
    with reservation_id.

    **Context**

    ``online_players``
        A query using the :model:`quiz.Player` manager.
    ``question``
        An instance of :model:`quiz.Question`.
    ``form``
        An instance of AnswerCreationForm.
    ``available_questions``
        A query using the :model:`quiz.Question` manager.
    ``disable_form``
        A boolean for disable the button form.
    ``answer_id``
        An id of a :model:`quiz.Answer` object.

    **Template:**

    :template:`quiz/question/answer.html`
    """
    page_template = 'quiz/question/answer.html'

    # Security checks
    try:
        question = Question.objects.get(pk=question_id)
        reservation = Reservation.objects.get(pk=reservation_id)

    except (KeyError, Question.DoesNotExist, Reservation.DoesNotExist):
        # TODO: display a message
        return HttpResponseRedirect(reverse('quiz:question_home'))

    # Get the player who won the reservation
    player = reservation.player

    # Default values: no answers and no form visible
    answer = None

    # This is used to make something visual in the template to indicate
    # that the player has to wait admin
    disable_form = False

    # If data from the post is provided
    if request.method == 'POST':
        # Create an AnswerCreationForm from POST data
        form = AnswerCreationForm(request.POST)

        # First we have to check if an answer already exist.
        # Note: only one answer allowed at this moment.
        if Answer.objects.filter(question=question).count() == 0:
            # If data is valid, create an Answer object
            if form.is_valid():
                answer = form.save(commit=False)

                # Link answer to question and player
                # TODO: Probably there's a better way
                answer.question = question
                answer.player = player

                answer.save()

                disable_form = True

            else:
                disable_form = False

    else:
        # You should think that now an empty form should be created.
        # Usually it is, but there's some cases in which the player
        # has already made an answer, then came back here.
        # In this case it's better to show his/here previous answer

quiz/templates/quiz/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style type="text/css">
      form .alert ul li {
        list-style: none;
      }

      form .alert ul {
        margin: 0;
        padding: 0;
      }
    </style>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


    <title>{% block title %}Python Quiz{% endblock %}</title>
  </head>
  <body>

    <!--
      Django-bootstrap tutorial: https://simpleisbetterthancomplex.com/videos/2018/11/04/django-auth-video-tutorial.html
    -->

    <!-- Navigation bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">

      <div class="container">
        <a class="navbar-brand" href="{% url 'quiz:index' %}">Quiz Game</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'quiz:question_home' %}">Home</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            {% if user.is_authenticated %}
            <ul class="navbar-nav mr-auto">
              <li class="nav-item dropdown">
                <div class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ user.nickname }}
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <!--<div class="dropdown-divider"></div>-->
                    <a class="dropdown-item" href="{% url 'quiz:logout' %}">Logout</a>
                  </div>
                </div>
              </li>
            </ul>
            {% else %}
            <a href="{% url 'quiz:login' %}" class="btn btn-outline-secondary">Login</a>
            <a href="{% url 'quiz:signup' %}" class="btn btn-primary ml-2">Sign Up</a>
            {% endif %}
          </form>
        </div>
      </div>
    </nav>

    <div class="container">
      
      <div class="row">

        <!-- Left side: players -->
        <div class="col">
          {% block players_block %}
          {% endblock %}
        </div>

        <!-- Center: question card -->
        <div class="col-6 justify-content-center">
          {% block main_content %}
          {% endblock %}
        </div>


        <!-- Right Card: alerts -->
        <div class="col">          
          {% block alerts_block %}
          {% endblock %}
        </div>

<!--           <script type="text/javascript">
            // Hide alerts
            $(document).ready(function(){
                $('.alert').alert('close');
            });
          </script> -->

      </div>

    </div>

    {% block extra_javascript_block %}
    {% endblock %}

   </body>
</html>

quiz/templates/quiz/index.html
{% extends "quiz/base.html" %}

{% block main_content %}


  <div class="jumbotron">
    <h1 class="display-4">Quiz Game!</h1>
    <p class="lead">Welcome to the Python Quiz Game: a simple quiz game written in Python(3) and Django.</p>
    <hr class="my-4">

    {% if not user.is_authenticated %}

    <p>
        Do you want to play but it's your first time here?
        Sign up to create an account. Only a nickname and a password are required.
    </p>
      <p>
        Do you already have an account? Log in and start answering questions.
      </p>

      {% else %}

    <p>
        It seems that you are already logged in. What are you waiting for?
        Go to the <strong>Home page</strong> and start playing.
    </p>
    <a class="btn btn-primary btn-lg" href="{% url 'quiz:question_home' %}" role="home">Home</a>

      {% endif %}
  </div>


{% endblock %}